spring:
  application:
    name: payment-service

  config:
    import: "configserver:http://${CONFIG_SERVER_HOST}"
  profiles:
    active: local

  cloud:
    config:
      username: ${CONFIG_USERNAME}
      password: ${CONFIG_PASSWORD}
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000

# Toss Payments
toss:
  secret-key: ${TOSS_SECRET_KEY}

# Feign Client
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

# Service Destinations (for Feign) - Eureka 사용으로 변경 예정
service:
  store:
    url: ${STORE_SERVICE_URL}
