spring:
  application:
    name: discovery-service

  config:
    import: "configserver:http://${CONFIG_SERVER_HOST}"
  profiles:
    active: local

  cloud:
    config:
      username: ${CONFIG_USERNAME}
      password: ${CONFIG_PASSWORD}
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000

eureka:
  client:
    register-with-eureka: false     # Do not register itself
    fetch-registry: false            # Do not fetch registry
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false  # Disable self-preservation for development
    eviction-interval-timer-in-ms: 3000  # Eviction interval (3 seconds)
