spring:
  application:
    name: animal-service

  profiles:
    active: dev

  # Spring Batch Settings
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false  # REST API로 수동 실행
  elasticsearch:
    connection-timeout: 5s
    socket-timeout: 30s
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

# Server Settings
server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Logging Settings
logging:
  level:
    com.pawbridge.animalservice: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.batch: DEBUG
    org.springframework.boot.autoconfigure.batch: DEBUG
    org.springframework.data.elasticsearch.client.elc: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"



# Batch Scheduler Settings
# Batch Scheduler Settings (Custom)
batch:
  apms:
    sync:
      # Cron 표현식: 매일 새벽 2시 실행
      cron: "0 0 2 * * ?"

# APMS Public API Settings
apms:
  api:
    base-url: ${APMS_API_BASE_URL}
    service-key: ${APMS_API_SERVICE_KEY}

# K8s Probe 설정 (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
