spring:
  application:
    name: store-service

  config:
    import: "configserver:http://${CONFIG_SERVER_HOST}"
  profiles:
    active: local

  cloud:
    config:
      username: ${CONFIG_USERNAME}
      password: ${CONFIG_PASSWORD}
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_BUCKET_NAME}

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100 # N+1 문제 완화 (Batch Size)

  # Kafka Consumer/Producer 상세 설정 (bootstrap-servers는 Config Repository에서)
  kafka:
    consumer:
      group-id: store-service-group
      auto-offset-reset: earliest


