name: Deploy User Service

on:
  push:
    branches: [ "dev" ]
    paths:
      - 'user-service/**' # 이 폴더가 변했을 때만 실행!
      - '.github/workflows/deploy-user.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 1. 빌드 (해당 폴더로 이동해서 실행)
      - name: Build User Service
        run: |
          cd user-service  # 해당 서비스 폴더로 이동
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 2. 이미지 빌드 & 푸시
      - name: Build & Push Docker Image
        run: |
          cd user-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest

      # 3. 배포 (Node-2로 전송)
      - name: Deploy to Node-3
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST_2 }} # User는 Node-2
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/deploy
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" > .env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
            echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            
            # JWT
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "JWT_ACCESS_TOKEN_EXPIRATION=${{ secrets.JWT_ACCESS_TOKEN_EXPIRATION }}" >> .env
            echo "JWT_REFRESH_TOKEN_EXPIRATION=${{ secrets.JWT_REFRESH_TOKEN_EXPIRATION }}" >> .env
            
            # OAuth
            echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
            echo "GOOGLE_SECRET_KEY=${{ secrets.GOOGLE_SECRET_KEY }}" >> .env
            echo "REDIRECT_URI=${{ secrets.REDIRECT_URI }}" >> .env
            echo "OAUTH2_REDIRECT_URI=${{ secrets.OAUTH2_REDIRECT_URI }}" >> .env
            
            # Email (변수명 변환!)
            echo "GOOGLE_EMAIL=${{ secrets.MAIL_USERNAME }}" >> .env
            echo "GOOGLE_EMAIL_SECRET_KEY=${{ secrets.MAIL_PASSWORD }}" >> .env
            
            # DB_USER_URL 정의: Node-2 내부 DB(mysql) 연결 주소
            echo "DB_USER_URL=jdbc:mysql://mysql:3306/pawbridge_user?useSSL=false&allowPublicKeyRetrieval=true" >> .env
            
            # 프라이빗 IP 주입
            echo "NODE1_PRIVATE_IP=${{ secrets.NODE1_PRIVATE_IP }}" >> .env
            echo "NODE2_PRIVATE_IP=${{ secrets.NODE2_PRIVATE_IP }}" >> .env
            echo "NODE3_PRIVATE_IP=${{ secrets.NODE3_PRIVATE_IP }}" >> .env
            
            # 실행
            docker compose pull user-service
            docker compose up -d --no-deps user-service
            docker image prune -f